# This file was generated by GoReleaser. DO NOT EDIT.
class Nftresolve < Formula
  desc "Helper script to display metadata of NFT token"
  homepage ""
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/elek/nftresolve/releases/download/1.0.0/nftresolve_1.0.0_darwin_x86_64.tar.gz"
    sha256 "d5eb52463caed4e6cebfa951e986cfa6a6b9fb4ea71d101792c9980d4f9f92d8"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/elek/nftresolve/releases/download/1.0.0/nftresolve_1.0.0_linux_x86_64.tar.gz"
      sha256 "bd9e9e6919c055c7bca75b5c2f2a55efab17a8460541ffc3a79887277f9c068b"
    end
  end

  def install
    bin.install "nftresolve"
  end
end
